### ISSUE TITLE
Unable to use dsEng Expand R2023x FD04

### ISSUE THREAD

**Issue by AndreasX10D** [3ds-cpe-emed/ws3dx-dotnet#49]
class: ws3dx.dseng.core.service.EngItemService
method: Expand

In 2024x_fd02 repo, the Expand method uses PostIndividualNoMask, but 2023x_fd04 uses PostIndividual.

Using PostIndividual, I get a "No Mask Schema Definition" error message.
Changing to PostIndividualNoMask fixes the problem.

**Comment by AndreasX10D** [comment]
Seems there is a deeper problem with the Expand method. There is no class implementing the IExpandResponse interface, causing the deserialization to fail.

**Comment by 3ds-cpe-emed** [comment]
Hi @AndreasX10D thanks for raising this. I am actually working on a major update that will require .NET 8.0. This will bring a more robust Deserialization engine/approach. Regarding the Expand one of the main issues is that there is no defined fixed json schema for it. So, at the moment if you need to use it you will need to provide your own implementation.

**Comment by AndreasX10D** [comment]
Thanks for letting me know! And thanks for this piece of fantastic code. I'll write my own implementation of Expand and looking forward to an updated version in the future.

**Comment by 3ds-cpe-emed** [comment]
Thanks . I am always looking for improvement feedback or contributions. If there is no change in plans I hope to have time for a first version with the new release ready for the dseng (Engineering) corpus by the end of this week or at the beginning of next. The other corpus (dsmfg, ...) will follow but later on.

**Comment by 3ds-cpe-emed** [comment]
@AndreasX10D  please check the current major refactoring branch here [/dev/net8/main_oc_2024x_fd02](https://github.com/3ds-cpe-emed/ws3dx-dotnet/tree/dev/net8/main_oc_2024x_fd02) . Please check the Expand Unit Test in file [EngItemService_EngItem_UnitTest.cs](https://github.com/3ds-cpe-emed/ws3dx-dotnet/blob/dev/net8/main_oc_2024x_fd02/ws3dx.dseng/tests/service.tests/EngItemService_EngItem_UnitTest.cs) . 

In the future I intend to extend both the Expand response (deserialization) schema with a more strict schema (rather than just returning object/JsonElement) and also the input request schema (payload) particularly for filtering. Any ideas are welcomed.

**Comment by 3ds-cpe-emed** [comment]
I am closing this issue - please reopen if you don't think it's closed
